---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'MyTable'
      AttributeDefinitions:
        - AttributeName: 'PK'
          AttributeType: 'S'
        - AttributeName: 'SK'
          AttributeType: 'S'
        - AttributeName: 'Name'
          AttributeType: 'S'
        - AttributeName: 'Age'
          AttributeType: 'N'
        - AttributeName: 'Gender'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'PK'
          KeyType: 'HASH'
        - AttributeName: 'SK'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: 'AgeIndex'
          KeySchema:
            - AttributeName: 'Age'
              KeyType: 'HASH'
            - AttributeName: 'Name'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: 'ALL'
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      LocalSecondaryIndexes:
        - IndexName: 'GenderIndex'
          KeySchema:
            - AttributeName: 'PK'
              KeyType: 'HASH'
            - AttributeName: 'Gender'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: 'INCLUDE'
            NonKeyAttributes:
              - 'Name'

