AWSTemplateFormatVersion: 2010-09-09

Resources:
  EC2ApacheInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0518bb0e75d3619ca
      InstanceType: t2.micro
      Tags:
        - Key: Env
          Value: Dev
        - Key: Name
          Value: Apache Web Server
      UserData: 
        Fn::Base64:
          !Sub |
            #!/bin/sh
            yum update -y
            yum install httpd.x86_64 -y
            systemctl start httpd.service
            systemctl enable httpd.service
            echo "hello from mycloudtutorials.com - $(curl http://169.254.169.254/latest/meta-data/public-ipv4)" > /var/www/html/index.html
      SecurityGroups:
        - !Ref ApacheSecurityGroup
      KeyName: "mycloudtutorials"

  ApacheSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "Apache Security Group"
      GroupDescription: Apacche security Group
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
          FromPort: 22
          ToPort: 22
        - IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
          FromPort: 80
          ToPort: 80
        - IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
          FromPort: 443
          ToPort: 443